// Generated by https://quicktype.io

export interface DeviceID {
    "soapenv:Envelope"?:      SoapenvEnvelope;
}

export interface SoapenvEnvelope {
    "soapenv:Body"?:   SoapenvBody;
}

export interface SoapenvBody {
    DLHR_DEVICE_RESP?: DlhrDeviceResp;
}

export interface DlhrDeviceResp {
    dls_device_id?: string;
}
