// Generated by https://quicktype.io

export interface ErrorResponse {
    "SOAP-ENV:Envelope":     SOAPENVEnvelope;
}

export interface SOAPENVEnvelope {
    "SOAP-ENV:Body":   SOAPENVBody;
}

export interface SOAPENVBody {
    "SOAP-ENV:Fault": SOAPENVFault;
}

export interface SOAPENVFault {
    faultcode:   string;
    faultstring: string;
    detail:      Detail;
}

export interface Detail {
    CIFault: CIFault;
}

export interface CIFault {
    IBResponse: IBResponse[];
}

export interface IBResponse {
    DefaultTitle:      string;
    StatusCode:        string;
    MessageSetID:      string;
    MessageID:         string;
    DefaultMessage:    string;
    MessageParameters: MessageParameters;
}

export interface MessageParameters {
    keyinformation: Keyinformation;
}

export interface Keyinformation {
    BUSINESS_UNIT: string;
    DL_NTARJETA:   string;
}
