// Generated by https://quicktype.io

export interface PromptObserve {
  "soapenv:Envelope": SoapenvEnvelope;
}

export interface SoapenvEnvelope {
  "soapenv:Body": SoapenvBody;
}

export interface SoapenvBody {
  DLHR_OBSERVE_PROMPT: DlhrObservePrompt;
}

export interface DlhrObservePrompt {
  DLHR_EMPL_BUSSINES_UNIT: DlhrEmplBussinesUnit;
  DLHR_ORIGEN:             DlhrOrigen;
  DLHR_EQUIP_TBL:          DlhrEquipTbl;
  DLHR_CUSTOMER:           DlhrCustomer;
  DLHR_OBSERVE_EMPLID:     DlhrObserveEmplid;
  DLHR_PUESTO:             DlhrPuesto;
  DLHR_SECTOR:             DlhrSector;
  DLHR_APS:                DlhrAps;
  DLHR_TURNO:              DlhrTurno;
}

export interface DlhrAps {
  DL_ACTION_NBR: string;
  EMPLID:        string;
  NOMBRE:        string;
}

export interface DlhrCustomer {
  DL_CUSTOMER_ID: number;
  DESCR:          string;
}

export interface DlhrEmplBussinesUnit {
  DLHR_OBSERVE_EMPLID: DlhrObserveEmplid;
  DLHR_BUSSINES_UNIT:  DlhrBussinesUnit;
}

export interface DlhrBussinesUnit {
  UNIDAD_DE_NEGOCIO: string;
  DESCR:             string;
}

export interface DlhrObserveEmplid {
  EMPLID: string;
  NOMBRE: string;
}

export interface DlhrEquipTbl {
  DL_EQUIPEMENT_ID: string;
  DESCR:            string;
}

export interface DlhrOrigen {
  ORIGEN: number;
  DESCR:  string;
}

export interface DlhrPuesto {
  DL_PUESTO: string;
  DESCR:     string;
}

export interface DlhrSector {
  DL_SECTOR_ID: string;
  DESCR:        string;
}

export interface DlhrTurno {
  DL_TURNO: number;
  DESCR:    string;
}

// Generated by https://quicktype.io

export interface AllObserve {
  "soapenv:Envelope": SoapenvEnvelopeAllObserve;
}

export interface SoapenvEnvelopeAllObserve {
  "soapenv:Body": SoapenvBodyAllObserve ;
}

export interface SoapenvBodyAllObserve {
  DLHR_ALL_OBSERVE_COLL: DlhrAllObserveColl;
}

export interface DlhrAllObserveColl {
  DLHR_ALL_OBSERVE: DlhrAllObserve;
}

export interface DlhrAllObserve {
  BUSINESS_UNIT:  string;
  DL_IDENTIF_DT:  string;
  NroTarjeta:     string;
  IDEquipo:       number;
  DL_ORIGEN:      string;
  DL_OBSERVADOR:  string;
  DL_TURNO:       number;
  DL_CUSTOMER_ID: number;
  DL_SECTOR_ID:   string;
  DL_PUESTO:      string;
  DL_ADESTACAR:   string;
}